/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : user
 * Created : 03/18/2015 10:00:34
 */

package org.syfsyf.phototool.gui;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 * The Class Test.
 */
public class Test {

	/** The a. */
	private String a;
	
	/** The b. */
	private String b;

	/** The property change support. */
	private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

	/**
	 * Adds the property change listener.
	 *
	 * @param propertyName the property name
	 * @param listener the listener
	 */
	public void addPropertyChangeListener(String propertyName, PropertyChangeListener listener) {
		propertyChangeSupport.addPropertyChangeListener(propertyName, listener);
	}

	/**
	 * Removes the property change listener.
	 *
	 * @param propertyName the property name
	 * @param listener the listener
	 */
	public void removePropertyChangeListener(String propertyName, PropertyChangeListener listener) {
		propertyChangeSupport.removePropertyChangeListener(propertyName, listener);
	}

	/**
	 * Adds the property change listener.
	 *
	 * @param listener the listener
	 */
	public void addPropertyChangeListener(PropertyChangeListener listener) {
		propertyChangeSupport.addPropertyChangeListener(listener);
	}

	/**
	 * Removes the property change listener.
	 *
	 * @param listener the listener
	 */
	public void removePropertyChangeListener(PropertyChangeListener listener) {
		propertyChangeSupport.removePropertyChangeListener(listener);
	}

	/**
	 * Sets the a.
	 *
	 * @param a the a
	 */
	public void setA(String a) {
		String aOld = this.a;
		this.a = a;
		propertyChangeSupport.firePropertyChange("a", aOld, a);
	}

	/**
	 * Gets the a.
	 *
	 * @return the a
	 */
	public String getA() {
		return this.a;
	}

	/**
	 * Sets the b.
	 *
	 * @param b the b
	 */
	public void setB(String b) {
		String bOld = this.b;
		this.b = b;
		propertyChangeSupport.firePropertyChange("b", bOld, b);
	}

	/**
	 * Gets the b.
	 *
	 * @return the b
	 */
	public String getB() {
		return this.b;
	}
}
